// Auto-generated from index.html.
// DO NOT EDIT.

library index_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import '_from_packages/tilebasedwordsearch/components/main_panel.dart';
import '_from_packages/tilebasedwordsearch/components/game_panel.dart';
import '_from_packages/tilebasedwordsearch/components/new_game_panel.dart';
import '_from_packages/tilebasedwordsearch/components/high_scores_component.dart';
import 'dart:html';
import 'dart:async';
import 'package:asset_pack/asset_pack.dart';
import 'package:web_ui/web_ui.dart';
import '_from_packages/tilebasedwordsearch/tilebasedwordsearch.dart' as app;


// Original code


main() {
  app.initialize();
}

// Additional generated code
void init_autogenerated() {
  var __root = autogenerated.document.body;
  final __html0 = new autogenerated.Element.html('<div is="main-panel"></div>'), __html1 = new autogenerated.Element.html('<div is="game-panel"></div>'), __html2 = new autogenerated.Element.html('<div is="new-game-panel"></div>'), __html3 = new autogenerated.Element.html('<div is="high-scores-panel"></div>');
  var __e1, __e3, __e5, __e7;
  var __t = new autogenerated.Template(__root);
  __e1 = __root.nodes[1];
  __t.conditional(__e1, () => app.currentPanel == 'main', (__t) {
    var __e0;
    __e0 = __html0.clone(true);
    __t.component(new MainPanel()..host = __e0);
  __t.addAll([new autogenerated.Text('\n      '),
      __e0,
      new autogenerated.Text('\n    ')]);
  });

  __e3 = __root.nodes[3];
  __t.conditional(__e3, () => app.currentPanel == 'game', (__t) {
    var __e2;
    __e2 = __html1.clone(true);
    __t.oneWayBind(() => app.dictionary, (e) { if (__e2.xtag.dictionary != e) __e2.xtag.dictionary = e; }, false, false);
    __t.oneWayBind(() => app.letterAtlas, (e) { if (__e2.xtag.letterAtlas != e) __e2.xtag.letterAtlas = e; }, false, false);
    __t.component(new GamePanel()..host = __e2);
  __t.addAll([new autogenerated.Text('\n      '),
      __e2,
      new autogenerated.Text('\n    ')]);
  });

  __e5 = __root.nodes[5];
  __t.conditional(__e5, () => app.currentPanel == 'newGame', (__t) {
    var __e4;
    __e4 = __html2.clone(true);
    __t.component(new NewGamePanel()..host = __e4);
  __t.addAll([new autogenerated.Text('\n      '),
      __e4,
      new autogenerated.Text('\n    ')]);
  });

  __e7 = __root.nodes[7];
  __t.conditional(__e7, () => app.currentPanel == 'highScores', (__t) {
    var __e6;
    __e6 = __html3.clone(true);
    __t.component(new HighScoresComponent()..host = __e6);
  __t.addAll([new autogenerated.Text('\n      '),
      __e6,
      new autogenerated.Text('\n    ')]);
  });

  __t.create();
  __t.insert();
}

//@ sourceMappingURL=main.dart.map