// Auto-generated from high_scores_component.html.
// DO NOT EDIT.

library high_scores_panel;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:web_ui/web_ui.dart';



class HighScoresComponent extends WebComponent {
  /** Autogenerated from the template. */

  /** CSS class constants. */
  static Map<String, String> _css = {};

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("high-scores-panel");
  static final __html1 = new autogenerated.Element.html('<ul>\n            <template></template>\n          </ul>'), __html2 = new autogenerated.LIElement(), __shadowTemplate = new autogenerated.DocumentFragment.html('''
        <h2>High Scores</h2>
        <template></template>
        <template></template>
      ''');
  autogenerated.Element __e12, __e13;
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("high-scores-panel");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __e12 = __root.nodes[3];
    __t.conditional(__e12, () => highScores.length > 0, (__t) {
      var __e10, __e11;
      __e11 = __html1.clone(true);
      __e10 = __e11.nodes[1];
      __t.loop(__e10, () => highScores, ($list, $index, __t) {
        var score = $list[$index];
        var __e9;
        __e9 = __html2.clone(true);
        var __binding8 = __t.contentBind(() =>  score , false);
        __e9.nodes.add(__binding8);
      __t.addAll([new autogenerated.Text('\n              '),
          __e9,
          new autogenerated.Text('\n            ')]);
      });
    __t.addAll([new autogenerated.Text('\n          '),
        __e11,
        new autogenerated.Text('\n        ')]);
    });

    __e13 = __root.nodes[5];
    __t.conditional(__e13, () => highScores.length <= 0, (__t) {
    __t.add(new autogenerated.Text('\n          No high scores yet.\n        '));
    });

    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = __e12 = __e13 = null;
  }

  /** Original code from the component. */

  List<int> highScores = <int>[];
}
//@ sourceMappingURL=high_scores_component.dart.map