// Auto-generated from main_panel.html.
// DO NOT EDIT.

library main_panel;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:web_ui/web_ui.dart';
import '../tilebasedwordsearch.dart' as app;



// Main landing page for the game.
// Includes:
// - "start new" button
// - "inprogress" list
// - "highscores" button or reference to panel.
class MainPanel extends WebComponent {
  /** Autogenerated from the template. */

  /** CSS class constants. */
  static Map<String, String> _css = {};

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("main-panel");
  static final __shadowTemplate = new autogenerated.DocumentFragment.html('''
        <h2>Main Panel</h2>
        <button>Show high scores</button>
        <button>New game</button>
      ''');
  autogenerated.ButtonElement __e14, __e15;
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("main-panel");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __e14 = __root.nodes[3];
    __t.listen(__e14.onClick, ($event) { app.currentPanel = 'highScores'; });
    __e15 = __root.nodes[5];
    __t.listen(__e15.onClick, ($event) { app.currentPanel = 'newGame'; });
    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = __e14 = __e15 = null;
  }

  /** Original code from the component. */


}
//@ sourceMappingURL=main_panel.dart.map